name: check
on:
  workflow_run:
    workflows: ["Deploy to UAT"]
    types:
      - completed

jobs:
  verify:
    runs-on: test

    steps:
     - name: 
       run: |
          sleep 5
          if docker ps -q --filter "publish=8787" | grep -q .; then
            CON_ID=$(docker ps -q --filter "publish=8787")
            echo "Container : $CON_ID is running"
          else
            echo "Check deployment : NO CONTAINER DEPLOYED"
            exit 1
          fi