name: Java CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-test:

    runs-on: test

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}

      - name: Build Application
        run: mvn clean package -DskipTests

      - name: Run Unit Tests
        run: mvn test

      - name: Upload Build Artifact  
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

      - name: Build Docker image
        run: |
          docker build -t java-app-test:${{ github.sha }} .

      - name: Stop Existing Container
        run: |
          if docker ps -q --filter "publish=8787" | grep -q .; then
            echo "Stopping container running on port 8787"
            docker ps -q --filter "publish=8787" | xargs -r docker rm -f
          else
            echo "No container running on port 8787"
          fi

      - name:
        run: |
          docker run -d -p 8787:8787 --name test-jva-${{ github.sha }} java-app-test:${{ github.sha }}
