name: Deploy to UAT

on:
  workflow_run:
    workflows: ["Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: test

    steps:
      - name: Stop Existing Container
        run: |
          if docker ps -q --filter "publish=8787" | grep -q .; then
            echo "Stopping container running on port 8787"
            docker ps -q --filter "publish=8787" | xargs -r docker rm -f
          else
            echo "No container running on port 8787"
          fi

      - name: Debug SHA
        run: |
          echo "SHORT_SHA=$SHORT_SHA"

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name:
        run: |
          docker run -d -p 8787:8787 --name test-java-$SHORT_SHA registry.mygitlab.example.com/root/java:$SHORT_SHA
